version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  agent:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent-1
    depends_on:
      - jenkins
    environment:
      # This points the agent to the controller service by service name
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent-1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    restart: unless-stopped

volumes:
  jenkins_home:
