name: declarative-example/main
on:
  workflow_dispatch:
jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo "Preparing workspace on ${{ env.NODE_NAME }}"
  Build:
    runs-on: ubuntu-latest
    needs: Prepare
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Hello from Declarative Jenkinsfile!
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running quick smoke test (noop)
  Publish:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Publish step (no-op in example)
  Post-Build:
    if: always()
    name: Post Build
    runs-on: ubuntu-latest
    needs:
    - Prepare
    - Build
    - Test
    - Publish
    steps:
    - name: echo message
      run: echo Pipeline finished.
      if: always()
